source('data_source.R')
need_data <- load_Data()
jpeg(filename='plot4.jpg', width=480, height=480, units='px')
par(mfrow=c(2,2))
plot(need_data$withtime, need_data$Global_active_power, type="l", col="black", xlab="", ylab="Global Active Power")
plot(need_data$withtime, need_data$Voltage, type="l", col="black", xlab="datetime", ylab="Voltage")
plot(need_data$withtime, need_data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(need_data$withtime, need_data$Sub_metering_2, type="l", col="red")
lines(need_data$withtime, need_data$Sub_metering_3, type="l", col="blue")
legend("topright", legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), col=c('black', 'red', 'blue'), lty=c(1, 1, 1))
plot(need_data$withtime, need_data$Global_reactive_power, type="l", col="black", xlab="datetime", ylab="Global_reactive_power")
dev.off()