source('data_source.R')
need_data <- load_Data()
jpeg(filename='plot2.jpg', width=480, height=480, units='px')
plot(need_data$withtime, need_data$Global_active_power, type="l", col="black", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()