source('data_source.R')
need_data <- load_Data()
jpeg(filename='plot3.jpg', width=480, height=480, units='px')
plot(need_data$withtime, need_data$Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering")
lines(need_data$withtime, need_data$Sub_metering_2, col="red")
lines(need_data$withtime, need_data$Sub_metering_3, col="blue")
legend("topright", legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), col=c('black', 'red', 'blue'), lty=c(1, 1, 1))
dev.off()
